name: oceantracker-dev
channels:
- conda-forge
- defaults
dependencies:
- python>=3.10
- numba
- numpy
- netcdf4
- xarray
- scipy
- pyproj
- psutil
- matplotlib
- pyyaml
- ffmpeg-python
- ipykernel
- requests
- build
- twine
- sphinx>=7.0
- sphinx-toolbox>=3.3.0
- nbsphinx
- ipython
- rst2pdf
- pytest>=7.0
- pytest-xdist
- coverage
- pytest-cov
- jupyter
- nbclient
- ffmpeg
- jupyter
- jupyterlab
- ipykernel
- ipywidgets
- git
- make
- pip
- pip:
  - -e .[dev]
